/*
    The Plasma splash screen — plan/17.

    The second half of one picture. config/splash/splash.c has been holding the brand mark on
    the screen since the first modeset; this is the same mark, at the same proportions, running
    the same layer pulse, for the window between the login and a painted desktop. The geometry
    and the animation constants are NOT restated here — Design.qml is generated by
    config/branding/make-splash-assets.py from the very constants the boot splash is composed
    with, so a change to the design reaches both splashes or neither.

    THE FADE IN is this file's. `stage` is written by SplashWindow::setStage; on Wayland stage 2
    ("wm") is set in SplashApp's constructor, so it arrives as soon as the QML has loaded, which
    is exactly the moment to start revealing. The BACKGROUND is opaque from the first frame and
    only the content fades: the window is a layer-shell overlay, and fading the whole thing in
    would show a moment of whatever kwin has on the screen underneath.

    THE FADE OUT is not, and cannot be. SplashApp::setStage() calls QGuiApplication::exit() when
    the "desktop" stage arrives and only then pushes stage 6 to the windows, so the event loop
    is already unwound before any animation this file started could render a frame. What
    actually fades the splash away is kwin's `login` effect — 500ms of opacity on windowClosed,
    matched by windowClass "ksplashqml ksplashqml", EnabledByDefault and shipped in
    /usr/share/kwin-wayland/effects/login. Stage 40 asserts the effect is there and still
    enabled by default, because losing it would not break anything: the splash would simply
    vanish instead of fading, on a screen no automated test can see.
*/

import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root

    // Opaque from the first frame; see the header.
    color: design.background

    // Written by SplashWindow::setStage().
    property int stage

    // Design pixels -> this screen. The boot splash approximates this with two discrete sprite
    // scales because it ships raster tiles; a vector splash can just be proportional, and on
    // the two cases that matter — a 1080p panel, and a 4K panel at the 2x scale factor Plasma
    // gives it — the two agree exactly. The floor stops the mark disappearing on a small
    // virtual display.
    readonly property real s: Math.max(0.6, height / design.baselineHeight)

    // Animation "B · Layer pulse": each slab dims and recovers inside its own third of the
    // cycle, the wave travelling up the stack, and all three sit at full brightness at cycle 0.
    // Identical to pulse_level() in config/splash/splash.c, deliberately including the
    // smoothstep-over-a-triangle shape rather than a sine.
    property real cycle: 0
    function slabOpacity(phase, slot) {
        let u = phase - slot / design.pulseSlots;
        if (u < 0) {
            u += 1;
        }
        u *= design.pulseSlots;
        if (u >= 1) {
            return 1;   // between pulses: at rest
        }
        const v = 1 - Math.abs(2 * u - 1);
        return 1 - design.pulseDepth * (v * v * (3 - 2 * v));
    }

    Design {
        id: design
    }

    NumberAnimation on cycle {
        from: 0
        to: 1
        duration: design.pulseCycleMs
        loops: Animation.Infinite
        // Honouring the user's animation setting the way Breeze's own splash does. With this
        // stopped `cycle` stays 0, which is the frame where every slab is at full — so turning
        // animations off gives the still mark rather than a mark frozen part-way through a dip.
        running: Kirigami.Units.longDuration > 1
    }

    Item {
        id: content

        anchors.centerIn: parent
        // build_block(): the block is as wide as its widest part and as tall as the mark box,
        // the gap and the wordmark stacked.
        width: Math.max(design.slabWidth, design.wordmarkWidth) * root.s
        height: (design.markBox + design.gap + design.wordmarkHeight) * root.s
        opacity: 0

        Item {
            id: mark

            // The mark is centred inside the layout box rather than filling it.
            width: design.slabWidth * root.s
            height: design.slabHeight * root.s
            anchors.horizontalCenter: parent.horizontalCenter
            y: (design.markBox * root.s - height) / 2

            // The three slabs are drawn on an identical canvas so they stack in register —
            // which is why all three simply fill this Item. Slot 0 dips first and the wave
            // travels up, so the bottom slab leads; the sprite container carries the same slots
            // in its tile flags.
            Image {
                anchors.fill: parent
                source: "images/slab-bot.svg"
                sourceSize: Qt.size(mark.width, mark.height)
                opacity: root.slabOpacity(root.cycle, 0)
            }
            Image {
                anchors.fill: parent
                source: "images/slab-mid.svg"
                sourceSize: Qt.size(mark.width, mark.height)
                opacity: root.slabOpacity(root.cycle, 1)
            }
            Image {
                anchors.fill: parent
                source: "images/slab-top.svg"
                sourceSize: Qt.size(mark.width, mark.height)
                opacity: root.slabOpacity(root.cycle, 2)
            }
        }

        Image {
            source: "images/wordmark.svg"
            anchors.horizontalCenter: parent.horizontalCenter
            y: (design.markBox + design.gap) * root.s
            width: design.wordmarkWidth * root.s
            height: design.wordmarkHeight * root.s
            sourceSize: Qt.size(width, height)
        }
    }

    OpacityAnimator {
        id: reveal

        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }

    property bool revealed: false
    onStageChanged: {
        // ">= 2" rather than Breeze's "== 2". ksplash's own README says stages may be added,
        // removed or reordered and that a stage can take zero time; an equality test against a
        // number that moved would leave this splash permanently invisible, which is the one
        // failure mode here nobody would see until a machine booted to a black screen.
        if (stage >= 2 && !revealed) {
            revealed = true;
            reveal.start();
        }
    }
}
